package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	manifestFile       = "project.json"
	generatedGoFile    = "internal/projectmeta/meta_generated.go"
	generatedFrontFile = "frontend/src/config/project.generated.js"
)

var (
	modulePattern  = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._~/-]*$`)
	slugPattern    = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]*$`)
	tokenPattern   = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	versionPattern = regexp.MustCompile(
		`^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$`,
	)
)

type ProjectManifest struct {
	GoModule    string `json:"goModule"`
	BinaryName  string `json:"binaryName"`
	AppName     string `json:"appName"`
	DisplayName string `json:"displayName"`
	Description string `json:"description"`
	Version     string `json:"version"`
	TokenPrefix string `json:"tokenPrefix"`
	FaviconPath string `json:"faviconPath"`
}

type goModEdit struct {
	Module struct {
		Path string
	}
}

type fileChange struct {
	path    string
	content []byte
}

func loadManifest(root string) (ProjectManifest, error) {
	content, err := os.ReadFile(filepath.Join(root, manifestFile))
	if err != nil {
		return ProjectManifest{}, err
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	var manifest ProjectManifest
	if err := decoder.Decode(&manifest); err != nil {
		return ProjectManifest{}, fmt.Errorf("decode %s: %w", manifestFile, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err == nil {
		return ProjectManifest{}, fmt.Errorf("decode %s: trailing JSON value", manifestFile)
	} else if !errors.Is(err, io.EOF) {
		return ProjectManifest{}, fmt.Errorf("decode %s: %w", manifestFile, err)
	}
	if err := validateManifest(manifest); err != nil {
		return ProjectManifest{}, err
	}
	return manifest, nil
}

func saveManifest(root string, manifest ProjectManifest) error {
	if err := validateManifest(manifest); err != nil {
		return err
	}
	content, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	content = append(content, '\n')
	return writeIfChanged(filepath.Join(root, manifestFile), content)
}

func validateManifest(manifest ProjectManifest) error {
	if !modulePattern.MatchString(manifest.GoModule) || strings.Contains(manifest.GoModule, "//") || strings.Contains(manifest.GoModule, "..") {
		return fmt.Errorf("invalid goModule %q", manifest.GoModule)
	}
	if !slugPattern.MatchString(manifest.BinaryName) {
		return fmt.Errorf("invalid binaryName %q", manifest.BinaryName)
	}
	if !slugPattern.MatchString(manifest.AppName) {
		return fmt.Errorf("invalid appName %q", manifest.AppName)
	}
	if strings.TrimSpace(manifest.DisplayName) == "" {
		return errors.New("displayName must not be empty")
	}
	if strings.TrimSpace(manifest.Description) == "" {
		return errors.New("description must not be empty")
	}
	if !versionPattern.MatchString(manifest.Version) {
		return fmt.Errorf("invalid version %q", manifest.Version)
	}
	if !tokenPattern.MatchString(manifest.TokenPrefix) {
		return fmt.Errorf("invalid tokenPrefix %q", manifest.TokenPrefix)
	}
	if !strings.HasPrefix(manifest.FaviconPath, "/") || strings.Contains(manifest.FaviconPath, "..") {
		return fmt.Errorf("invalid faviconPath %q", manifest.FaviconPath)
	}
	return nil
}

func generateProjectMetadata(root string, manifest ProjectManifest) error {
	if err := validateManifest(manifest); err != nil {
		return err
	}
	goContent, err := renderGoMetadata(manifest)
	if err != nil {
		return err
	}
	frontContent, err := renderFrontendMetadata(manifest)
	if err != nil {
		return err
	}
	if err := writeIfChanged(filepath.Join(root, generatedGoFile), goContent); err != nil {
		return err
	}
	return writeIfChanged(filepath.Join(root, generatedFrontFile), frontContent)
}

func renderGoMetadata(manifest ProjectManifest) ([]byte, error) {
	source := fmt.Sprintf(`// Code generated by projectctl; DO NOT EDIT.

package projectmeta

const (
	ModuleName = %s
	BinaryName = %s
	AppName = %s
	DisplayName = %s
	Description = %s
	Version = %s
	TokenPrefix = %s
	FaviconPath = %s
)
`,
		strconv.Quote(manifest.GoModule),
		strconv.Quote(manifest.BinaryName),
		strconv.Quote(manifest.AppName),
		strconv.Quote(manifest.DisplayName),
		strconv.Quote(manifest.Description),
		strconv.Quote(manifest.Version),
		strconv.Quote(manifest.TokenPrefix),
		strconv.Quote(manifest.FaviconPath),
	)
	return format.Source([]byte(source))
}

func renderFrontendMetadata(manifest ProjectManifest) ([]byte, error) {
	content, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, err
	}
	var result bytes.Buffer
	result.WriteString("// Code generated by projectctl; DO NOT EDIT.\n\n")
	result.WriteString("const projectMeta = Object.freeze(")
	result.Write(content)
	result.WriteString(")\n\nexport default projectMeta\n")
	return result.Bytes(), nil
}

func checkProject(root string, manifest ProjectManifest) error {
	if err := validateManifest(manifest); err != nil {
		return err
	}
	module, err := readGoModule(root)
	if err != nil {
		return err
	}
	if module != manifest.GoModule {
		return fmt.Errorf("go.mod module %q does not match project.json %q", module, manifest.GoModule)
	}

	expectedGo, err := renderGoMetadata(manifest)
	if err != nil {
		return err
	}
	expectedFront, err := renderFrontendMetadata(manifest)
	if err != nil {
		return err
	}
	if err := checkGeneratedFile(filepath.Join(root, generatedGoFile), expectedGo); err != nil {
		return err
	}
	if err := checkGeneratedFile(filepath.Join(root, generatedFrontFile), expectedFront); err != nil {
		return err
	}

	favicon := strings.TrimPrefix(filepath.ToSlash(filepath.Clean(manifest.FaviconPath)), "/")
	if favicon == "" || !fileExists(filepath.Join(root, "frontend", "public", filepath.FromSlash(favicon))) {
		return fmt.Errorf("favicon %q does not exist under frontend/public", manifest.FaviconPath)
	}
	return nil
}

func checkGeneratedFile(path string, expected []byte) error {
	actual, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated file %s: %w", path, err)
	}
	if !bytes.Equal(actual, expected) {
		return fmt.Errorf("generated file %s is stale; run projectctl generate", path)
	}
	return nil
}

func readGoModule(root string) (string, error) {
	cmd := exec.Command("go", "mod", "edit", "-json")
	cmd.Dir = root
	output, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	var edit goModEdit
	if err := json.Unmarshal(output, &edit); err != nil {
		return "", fmt.Errorf("decode go.mod metadata: %w", err)
	}
	if edit.Module.Path == "" {
		return "", errors.New("go.mod has no module path")
	}
	return edit.Module.Path, nil
}

func renameProject(root string, current ProjectManifest, next ProjectManifest) error {
	if err := validateManifest(next); err != nil {
		return err
	}
	changes, err := planGoImportChanges(root, current.GoModule, next.GoModule)
	if err != nil {
		return err
	}

	cmd := exec.Command("go", "mod", "edit", "-module="+next.GoModule)
	cmd.Dir = root
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("update go.mod: %w: %s", err, strings.TrimSpace(string(output)))
	}
	for _, change := range changes {
		if err := os.WriteFile(change.path, change.content, 0o644); err != nil {
			return err
		}
	}
	if err := saveManifest(root, next); err != nil {
		return err
	}
	if err := generateProjectMetadata(root, next); err != nil {
		return err
	}

	references, err := findIdentityReferences(root, current, next)
	if err != nil {
		return err
	}
	if len(references) > 0 {
		return fmt.Errorf("old identity remains in:\n%s", strings.Join(references, "\n"))
	}
	return checkProject(root, next)
}

func planGoImportChanges(root string, oldModule string, newModule string) ([]fileChange, error) {
	if oldModule == newModule {
		return nil, nil
	}
	var changes []fileChange
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != root && shouldSkipDirectory(root, path) {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".go" {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, content, parser.ParseComments)
		if err != nil {
			return err
		}
		changed := false
		for _, spec := range file.Imports {
			value, err := strconv.Unquote(spec.Path.Value)
			if err != nil {
				return err
			}
			if value == oldModule || strings.HasPrefix(value, oldModule+"/") {
				spec.Path.Value = strconv.Quote(newModule + strings.TrimPrefix(value, oldModule))
				changed = true
			}
		}
		if !changed {
			return nil
		}
		var formatted bytes.Buffer
		if err := format.Node(&formatted, fset, file); err != nil {
			return err
		}
		changes = append(changes, fileChange{path: path, content: formatted.Bytes()})
		return nil
	})
	return changes, err
}

func findIdentityReferences(root string, old ProjectManifest, next ProjectManifest) ([]string, error) {
	values := [][2]string{
		{old.GoModule, next.GoModule},
		{old.BinaryName, next.BinaryName},
		{old.AppName, next.AppName},
		{old.DisplayName, next.DisplayName},
		{old.Description, next.Description},
		{old.TokenPrefix, next.TokenPrefix},
		{old.FaviconPath, next.FaviconPath},
	}
	nextValues := []string{
		next.GoModule,
		next.BinaryName,
		next.AppName,
		next.DisplayName,
		next.Description,
		next.TokenPrefix,
		next.FaviconPath,
	}
	unique := make(map[string]struct{})
	for _, values := range values {
		if values[0] != values[1] && len(values[0]) >= 3 && !identityIsRetained(values[0], nextValues) {
			unique[values[0]] = struct{}{}
		}
	}

	var references []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != root && shouldSkipDirectory(root, path) {
				return filepath.SkipDir
			}
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		if relative == manifestFile || relative == "go.sum" || relative == "frontend/pnpm-lock.yaml" {
			return nil
		}
		if !isTextProjectFile(relative) {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for value := range unique {
			if bytes.Contains(content, []byte(value)) {
				references = append(references, fmt.Sprintf("%s: %q", relative, value))
			}
		}
		return nil
	})
	sort.Strings(references)
	return references, err
}

func identityIsRetained(oldValue string, nextValues []string) bool {
	for _, nextValue := range nextValues {
		if strings.Contains(nextValue, oldValue) {
			return true
		}
	}
	return false
}

func isTextProjectFile(path string) bool {
	if filepath.Base(path) == "go.mod" {
		return true
	}
	switch strings.ToLower(filepath.Ext(path)) {
	case ".go", ".js", ".ts", ".vue", ".html", ".md", ".json", ".sh", ".yaml", ".yml", ".toml", ".svg":
		return true
	default:
		return false
	}
}

func shouldSkipDirectory(root string, path string) bool {
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return false
	}
	relative = filepath.ToSlash(relative)
	if filepath.Base(path) == "node_modules" {
		return true
	}
	switch relative {
	case ".git", "frontend/dist", "build", "config", "data", "logs":
		return true
	default:
		return false
	}
}

func writeIfChanged(path string, content []byte) error {
	if current, err := os.ReadFile(path); err == nil && bytes.Equal(current, content) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
